package com.jiapeng.mineguard.agent;

public enum PolicyViolationCode {
    INVALID_JSON,
    OUTPUT_TOO_LARGE,
    MISSING_FIELD,
    UNEXPECTED_FIELD,
    INVALID_FIELD_TYPE,
    INVALID_FIELD_VALUE,
    RULE_RISK_MISMATCH,
    RULE_DECISION_MISMATCH,
    RULE_APPROVAL_MISMATCH,
    RULE_REASON_CODES_MISMATCH,
    UNKNOWN_CITATION,
    CITATION_MISMATCH,
    FORBIDDEN_TOOL,
    TOOL_PLAN_MISMATCH,
    TOOL_ARGUMENT_MISMATCH
}
